// Static knowledge ported from dashboard-mockup.html.
// Live API data is overlaid on top of this where endpoints exist (hybrid mode).

// Rich per-source detail (keyed by youtube id) — overlays the live sources table.
export const SOURCE_DETAIL = {
  C2TcB5gxut8: { niche: 'kuliner', formula: 'process-reveal', tags: ['kuliner', 'faceless', 'hard-sub', 'satisfying'], dur: '44s', res: '1080x1920', lang: 'id', hook: 'curiosity (disuntik) + fakta unik', clip: true, face: false, sum: 'Faceless ID kuliner, milk-soaked Korean toast, hard-sub + VO.' },
  'D-6aL-OVvjw': { niche: 'entertainment', formula: 'street-interview-verdict', tags: ['street-interview', 'karaoke-caption', 'reveal-ditunda'], dur: '29s', res: '2160x3840', lang: 'en', hook: 'verdict caption + curiosity', clip: true, face: true, sum: 'Repurposed street-interview rizz/quiz w/ car reveal + karaoke caption.' },
  tSbLjWMz8LQ: { niche: 'restoration', formula: 'process-reveal', tags: ['restoration', 'satisfying', 'before-after', 'faceless'], dur: '157s', res: '2160x3840', lang: '—', hook: 'striking visual + before/after', clip: true, face: false, sum: 'Faceless lead-acid battery restoration, street workshop.' },
  E04NPubJ12U: { niche: 'comedy', formula: 'prank-reaction', tags: ['prank', 'couple', 'comedy', 'reaction'], dur: '51s', res: '360x640', lang: 'en', hook: 'POV curiosity + couple', clip: false, face: true, sum: 'Couple comedy/prank POV skit in a workshop.' },
  'Knely-osDJw': { niche: 'brand-teaser', formula: 'cryptic-invite-teaser', tags: ['cryptic', 'kinetic-typography', 'cinematic'], dur: '31s', res: '1080x1920', lang: 'en', hook: 'cryptic "this is a message"', clip: false, face: true, sum: 'Cinematic cryptic event-invite teaser, kinetic red typography.' }
}

// Agent rich detail (keyed by name) — overlays the live /dash/agents roster.
export const AGENT_DETAIL = {
  main: { trig: 'YouTube URL, "buat video tentang…"', detail: 'Bot Telegram default. Jalanin workflow lengkap + 6 knowledge module di SOUL.md (analysis read, formula library, script, clip, QC, producer).', model: ['ACTIVE BOT'], cls: ['s-active'] },
  analyze: { trig: '"analisa video ini", URL', detail: 'Workhorse. Tarik metadata + frame + transcript via pipeline-api, output per-frame + struktur + JSON tags. Butuh model vision.', model: ['vision', 'modul'], cls: ['m-vision', 's-mod'] },
  'analyze-senior': { trig: '"kenapa viral", "kasih formula"', detail: 'Strategist. Hook teardown, retention mechanics, formula yang bisa ditiru, engagement read jujur. Model opus (kualitas).', model: ['opus', 'modul'], cls: ['m-opus', 's-mod'] },
  scriptwriter: { trig: '"buatkan script", "voiceover"', detail: 'Judul+hashtag, hook 0-3s, beat-by-beat (visual+VO+caption), CTA, cold-open. Clone struktur, bukan kata.', model: ['sonnet', 'modul'], cls: ['m-sonnet', 's-mod'] },
  clipfinder: { trig: '"cari clip", "potong video panjang"', detail: 'Ranking momen: reaksi/payoff/money-shot/curiosity. Output rentang start–end + hook + cold-open + urutan upload.', model: ['sonnet', 'modul'], cls: ['m-sonnet', 's-mod'] },
  qcgate: { trig: '"QC", "layak posting?"', detail: 'Gate, bukan kritikus. FAIL hanya blocker (aspect salah/audio mati/caption ketutup UI/>60s/watermark). Major/minor = ship-but-improve.', model: ['sonnet', 'modul'], cls: ['m-sonnet', 's-mod'] },
  producer: { trig: '"selanjutnya ngapain?"', detail: 'Checklist [HUMAN]/[AUTOMATIC] per langkah + tool + estimasi menit + lever kualitas (ElevenLabs, CapCut, Submagic, prime time).', model: ['cheap', 'modul'], cls: ['m-cheap', 's-mod'] },
  editor: { trig: '"rakit", "gabungkan klip", "bikin compilation"', detail: 'Assembler. Input clips (clipfinder) + VO (scriptwriter) + stock sound → output EDL JSON (urutan clip, in/out, SFX@detik, caption timing, music −18dB). assemble.sh → ffmpeg render final 9:16.', model: ['sonnet', 'modul'], cls: ['m-sonnet', 's-mod'] }
}

// Kanban content_pieces — dummy (no endpoint yet).
export const PIECES = {
  mie: { title: 'Mie gang sempit', status: 'Draft', kind: 'scripted', niche: 'kuliner', qc: 'pending', col: 'Draft', pct: 12, assets: ['script ✓', 'footage ✗', 'voiceover ✗', 'caption ✗', 'final ✗'], note: 'Baru script (formula process-reveal). Butuh footage + VO.' },
  esteh: { title: 'Es teh jumbo viral', status: 'Draft', kind: 'scripted', niche: 'kuliner', qc: 'pending', col: 'Draft', pct: 12, assets: ['script ✓', 'footage ✗', 'voiceover ✗', 'caption ✗', 'final ✗'], note: 'Script siap. Hook "es teh 1 liter cuma 5rb".' },
  martabak: { title: 'Martabak 1000 layer', status: 'Draft', kind: 'compilation', niche: 'kuliner', qc: 'pending', col: 'Draft', pct: 12, assets: ['clips ✓ (4)', 'footage ✗', 'voiceover ✗', 'caption ✗', 'final ✗'], note: 'Kompilasi 4 clip dari 2 source. Belum dirangkai.' },
  taichan: { title: 'Sate taichan', status: 'Voiceover', kind: 'scripted', niche: 'kuliner', qc: 'pending', col: 'Voiceover', pct: 38, assets: ['script ✓', 'footage ✓', 'voiceover ⏳', 'caption ✗', 'final ✗'], note: 'VO lagi digenerate (ElevenLabs, voice ID terkunci).' },
  cireng: { title: 'Cireng crispy', status: 'Voiceover', kind: 'scripted', niche: 'kuliner', qc: 'pending', col: 'Voiceover', pct: 38, assets: ['script ✓', 'footage ✓', 'voiceover ⏳', 'caption ✗', 'final ✗'], note: 'Nunggu VO. Footage 9:16 sudah oke.' },
  setan: { title: 'Seblak setan', status: 'Editing', kind: 'scripted', niche: 'kuliner', qc: 'pending', col: 'Editing', pct: 60, assets: ['script ✓', 'footage ✓', 'voiceover ✓', 'caption ⏳', 'final ✗'], note: 'Edit di CapCut — caption hard-sub via Submagic, perlu proofread.' },
  dimsum: { title: 'Dimsum mercon', status: 'Editing', kind: 'compilation', niche: 'kuliner', qc: 'pending', col: 'Editing', pct: 60, assets: ['clips ✓ (3)', 'footage ✓', 'voiceover ✓', 'caption ⏳', 'final ✗'], note: 'Kompilasi 3 clip. Lagi sinkron caption ke beat VO.' },
  seblak: { title: 'Seblak viral', status: 'QC', kind: 'scripted', niche: 'kuliner', qc: 'PASS (86)', col: 'QC', pct: 82, assets: ['script ✓', 'footage ✓', 'voiceover ✓', 'caption ✓', 'final ✓'], note: 'Lolos QC. Siap jadwal posting 19:00 WIB.' },
  kerak: { title: 'Kerak telor', status: 'QC', kind: 'scripted', niche: 'kuliner', qc: 'FAIL — aspect 1:1', col: 'QC', pct: 82, fail: true, assets: ['script ✓', 'footage ✓', 'voiceover ✓', 'caption ✓', 'final ✓'], note: 'BLOCKER: rasio 1:1, harus 9:16. Re-export sebelum posting.' },
  bakso: { title: 'Bakso beranak', status: 'Published', kind: 'scripted', niche: 'kuliner', qc: 'PASS (91)', col: 'Published', pct: 100, assets: ['script ✓', 'footage ✓', 'voiceover ✓', 'caption ✓', 'final ✓'], note: 'Live di TikTok + YT Shorts + Reels. 1.2jt views, naik +18k/hari.' },
  dalgona: { title: 'Kopi dalgona', status: 'Published', kind: 'scripted', niche: 'kuliner', qc: 'PASS (84)', col: 'Published', pct: 100, assets: ['script ✓', 'footage ✓', 'voiceover ✓', 'caption ✓', 'final ✓'], note: 'TikTok + Reels. 340rb views.' },
  telur: { title: 'Telur gulung', status: 'Published', kind: 'scripted', niche: 'kuliner', qc: 'PASS (80)', col: 'Published', pct: 100, assets: ['script ✓', 'footage ✓', 'voiceover ✓', 'caption ✓', 'final ✓'], note: 'TikTok only. 89rb views — hook kurang kuat, catat buat next.' }
}
export const KANBAN_COLS = ['Draft', 'Voiceover', 'Editing', 'QC', 'Published']

// Posts schedule — dummy (no endpoint yet).
export const POSTS = [
  { konten: 'Seblak viral', platform: 'TikTok', jadwal: '16 Jun 19:00', status: 'scheduled', chip: 'c-analyzed', views: '—' },
  { konten: 'Seblak viral', platform: 'YT Shorts', jadwal: '16 Jun 19:00', status: 'scheduled', chip: 'c-analyzed', views: '—' },
  { konten: 'Mie gang sempit', platform: 'Reels', jadwal: '—', status: 'planned', chip: 'planned', views: '—' }
]

// Dashboard fallback movers (when DB is unreachable).
export const FALLBACK_MOVERS = [
  { title: 'Roti Bakar rendam susu', rate: '+1.9k', up: true },
  { title: 'How many miles is Crazy', rate: '+1.2k', up: true },
  { title: 'Dead Battery Revival', rate: '+780', up: true },
  { title: 'Ask your wife for help', rate: '+120', up: false }
]

// Full formula library (32) — knowledge base. `db:true` overlaid from live formulas table.
export const FORMULAS = [
  { slug: 'process-reveal', db: true, best: 'kuliner, repair, manufacturing (faceless)', face: '✅ faceless', struct: 'hook → before/kondisi → process ×4-6 (tiap beat 1 perubahan visual) → payoff money-shot ~75% → soft CTA', hook: 'visual mencolok / curiosity-cut text di atas proses', ret: 'gerakan terus + tegangan before/after; tahan money-shot paling lama', ex: 'Roti bakar rendam susu, restorasi aki' },
  { slug: 'price-reveal', db: false, best: 'kuliner reveal-harga, thrift, "worth it?"', face: '✅ faceless', struct: 'tunjukin barang/makanan → bangun penasaran "berapa?" → tunda → reveal harga bikin kaget → CTA "worth?"', hook: '"tebak harganya…" / angka disensor', ret: 'curiosity gap di harga; reveal ditunda sampai ~70%', ex: 'Mie gang sempit, jajanan sultan vs kaki lima' },
  { slug: 'did-you-know-fact', db: false, best: 'fakta unik, edukasi kuliner, "tau gak"', face: '✅ faceless', struct: 'klaim mengejutkan (hook) → bukti/visual → fakta tambahan ×2-3 → punchline fakta terbesar → CTA', hook: '"ternyata X itu…" / fakta kontra-intuitif', ret: 'tiap beat fakta baru; simpan fakta paling wow di akhir', ex: 'kasifakta — roti bakar Korea' },
  { slug: 'why-explainer', db: false, best: 'fakta "kenapa/mengapa X?", edukasi, curiosity', face: '✅ faceless', struct: 'hook pertanyaan "kenapa X?" → alasan 1 + visual → alasan ×2-3 → alasan utama / twist mengejutkan → CTA', hook: '"kenapa cewe Rusia cantik-cantik?" / pertanyaan provokatif', ret: 'otak pengin jawaban; tahan alasan terkuat di akhir', ex: 'kenapa orang Jepang langsing, kenapa cabai pedas' },
  { slug: 'before-after', db: false, best: 'transformasi, masak, glow-up, cleaning', face: '✅ faceless', struct: 'kondisi awal jelek/biasa → proses cepat (timelapse/cut) → reveal hasil dramatis → CTA', hook: 'split-screen before/after di detik 0', ret: 'kontras kuat; transisi mulus jadi "money moment"', ex: 'restorasi aki, deep-clean' },
  { slug: 'listicle-countdown', db: false, best: 'ranking, "5 X paling Y", rekomendasi', face: '✅ faceless', struct: 'janji daftar (hook "5 X…") → item #5→#2 cepat → build ke #1 → reveal #1 → CTA', hook: '"5 X yang…" + teaser #1', ret: 'rasa penasaran #1 menahan sampai akhir', ex: '5 jajanan viral, 3 mie terpedas' },
  { slug: 'asmr-satisfying', db: false, best: 'kuliner, masak, no-VO (sound-led)', face: '✅ faceless', struct: 'close-up + suara renyah/sizzle → proses ber-ritme → klimaks tekstur (cheese pull) → loop mulus', hook: 'suara + close-up tekstur di detik 0', ret: 'audio-driven; tanpa VO, captions minimal', ex: 'martabak 1000 layer, dimsum mercon' },
  { slug: 'tutorial-howto', db: false, best: 'resep, "cara bikin X", DIY', face: '✅ faceless', struct: 'hasil akhir dulu (hook) → bahan cepat → langkah ×4-5 → hasil → CTA "simpan resep"', hook: 'tunjukin hasil jadi → "cuma 3 bahan"', ret: 'value tinggi → di-save; langkah ringkas', ex: 'es teh jumbo, cireng crispy' },
  { slug: 'expectation-vs-reality', db: false, best: 'komedi ringan, kuliner, relatable', face: '⚠️ semi', struct: 'setup ekspektasi → cut → realita lucu/beda → punchline → loop', hook: '"ekspektasi vs realita" caption', ret: 'kontras jadi humor; cut tajam', ex: 'pesan online vs aslinya' },
  { slug: 'pov-storytime', db: false, best: 'relatable, drama mini, brand story', face: '⚠️ semi', struct: 'POV caption → bangun situasi → twist/relate → ending memuaskan', hook: '"POV: kamu…" + situasi relatable', ret: 'narasi menarik; caption sebagai panduan', ex: 'POV: pertama kali nyobain seblak setan' },
  { slug: 'street-interview-verdict', db: true, best: 'entertainment, repurpose ke reveal-harga', face: '⚠️ perlu on-cam', struct: 'verdict caption → open in-medias-res → bet/pertanyaan → reaksi + karaoke caption → reveal ditunda → loop', hook: 'verdict caption + curiosity gap', ret: 'back-and-forth + karaoke caption', ex: 'How many miles is Crazy' },
  { slug: 'cryptic-invite-teaser', db: true, best: 'brand/event teaser cinematic', face: '✅ faceless', struct: 'pesan kriptik → reveal kata-per-kata → pattern interrupt (bg gelap→terang) → twist → black-screen CTA', hook: '"this is a message" cinematic', ret: 'tipografi kinetik + misteri', ex: 'Cluely teaser' },
  { slug: 'prank-reaction', db: true, best: 'comedy (perlu talent, susah faceless)', face: '❌ on-cam', struct: 'POV/setup caption → bangun tegangan → reaksi (kaget/ketawa) → payoff', hook: 'POV curiosity + setup relatable', ret: 'tegangan → pelepasan emosi', ex: 'When you ask your wife for help' },
  { slug: 'comparison-vs', db: false, best: 'kuliner murah vs mahal, lokal vs import', face: '✅ faceless', struct: 'tampilkan 2 opsi (split) → bandingin beat-by-beat → reveal pemenang/harga → CTA "pilih mana?"', hook: '"Rp5rb vs Rp50rb, beda?"', ret: 'penonton pengin tau pemenang; debat di komen', ex: 'jajanan kaki lima vs resto' },
  { slug: 'tier-list-ranking', db: false, best: 'ranking jajanan, "tier list"', face: '✅ faceless', struct: 'tampilkan grid S/A/B/C → masukin item satu-satu + alasan singkat → item kontroversial terakhir → CTA "setuju?"', hook: '"tier list jajanan SD" + item ekstrem', ret: 'opini memancing komen; penasaran penempatan', ex: 'tier list mie instan' },
  { slug: 'mistake-warning', db: false, best: 'tips, "jangan lakuin ini", edukasi', face: '✅ faceless', struct: 'hook peringatan → kesalahan #1 + akibat → kesalahan ×2-3 → cara benar → CTA', hook: '"STOP, jangan masak X kayak gini"', ret: 'rasa takut salah + value tinggi → save', ex: '5 kesalahan goreng yang bikin gagal' },
  { slug: 'trend-hijack', db: false, best: 'apa aja — numpang sound/format viral', face: '✅ faceless', struct: 'pakai audio/format trending → adaptasi ke niche kamu → twist khas → CTA', hook: 'sound trending + konteks kuliner', ret: 'algoritma boost sound; familiar tapi baru', ex: 'transisi trending + reveal makanan' },
  { slug: 'mukbang-tasting', db: false, best: 'review makanan, reaksi nyobain', face: '⚠️ perlu tangan/mulut', struct: 'close-up makanan (hook) → gigitan pertama + reaksi → deskripsi rasa → verdict + CTA', hook: 'close-up + suara + "ini gila sih"', ret: 'ASMR + reaksi autentik', ex: 'nyobain seblak level 10' },
  { slug: 'challenge-experiment', db: false, best: '"aku coba X selama N hari", eksperimen', face: '✅ faceless', struct: 'premis ("7 hari makan X") → hari demi hari cepat → hasil/twist → CTA', hook: '"aku makan mie 7 hari, ini yang terjadi"', ret: 'penasaran hasil akhir menahan sampai habis', ex: '7 hari jajan kaki lima' },
  { slug: 'nostalgia-throwback', db: false, best: 'jajanan jadul, "anak 90an pasti tau"', face: '✅ faceless', struct: 'hook nostalgia → tampilkan jajanan jadul ×3-4 → momen "paling dikangenin" → CTA "masih ada?"', hook: '"jajanan 2000an yang punah"', ret: 'emosi nostalgia → share + tag teman', ex: 'jajanan SD yang hilang' },
  { slug: 'myth-busting', db: false, best: 'edukasi, "mitos vs fakta" kuliner', face: '✅ faceless', struct: 'sebut mitos populer → bantah dengan bukti/visual → fakta sebenarnya → CTA', hook: '"mitos: MSG bahaya. faktanya…"', ret: 'kontroversi ringan + edukasi → komen debat', ex: 'mitos makanan yang salah' },
  { slug: 'green-screen-react', db: false, best: 'react ke berita/screenshot/video lain', face: '⚠️ semi', struct: 'tempel media di belakang (green screen) → komentari poin demi poin → hot-take → CTA', hook: '"liat ini deh…" + visual mengejutkan', ret: 'konteks reaktif + opini', ex: 'react harga makanan absurd' },
  { slug: 'text-story-drama', db: false, best: 'drama relatable, chat screenshot', face: '✅ faceless', struct: 'tampilkan chat/teks per bubble → bangun konflik → twist → ending → CTA', hook: 'bubble chat pertama yang bikin penasaran', ret: 'pengin tau kelanjutan chat', ex: 'chat customer vs warung' },
  { slug: 'day-in-the-life', db: false, best: 'BTS warung, proses jualan', face: '✅ faceless', struct: 'mulai hari (hook) → beat aktivitas cepat → momen puncak (rame/laku) → refleksi singkat → CTA', hook: '"jam 4 pagi udah mulai…"', ret: 'voyeuristik + ritme; relate ke pejuang UMKM', ex: 'sehari jualan seblak' },
  { slug: 'hot-take-controversy', db: false, best: 'opini, "unpopular opinion"', face: '✅ faceless', struct: 'klaim berani/kontroversial (hook) → argumen ×2-3 → ajak debat → CTA "setuju?"', hook: '"unpopular opinion: X overrated"', ret: 'memancing komen pro-kontra (engagement)', ex: 'jajanan overrated' },
  { slug: 'this-or-that', db: false, best: 'pilihan cepat, interaktif', face: '✅ faceless', struct: 'rapid A vs B ×4-5 → pilihan terakhir susah → CTA "kamu pilih?"', hook: '"A atau B?" cepat', ret: 'partisipasi mental + komen jawaban', ex: 'mie vs nasi, manis vs pedas' },
  { slug: 'rate-everything', db: false, best: 'review, "rating 1-10"', face: '✅ faceless', struct: 'item → cicip/nilai cepat → skor + alasan singkat → item terakhir ekstrem → CTA', hook: '"rating jajanan SD, jujur"', ret: 'penasaran skor + opini', ex: 'rating 5 mie instan' },
  { slug: 'street-food-tour', db: false, best: 'lokasi, "Rp50rb keliling"', face: '⚠️ semi', struct: 'premis budget/lokasi → stop demi stop cepat → total/verdict → CTA', hook: '"Rp50rb bisa dapat apa di…"', ret: 'eksplorasi + budget challenge', ex: 'kuliner malam Rp50rb' },
  { slug: 'recipe-hack', db: false, best: 'tips dapur, "hack masak"', face: '✅ faceless', struct: 'masalah umum (hook) → hack cepat → before/after hasil → CTA "simpan"', hook: '"ternyata ada cara gampang…"', ret: 'value tinggi → save + share', ex: 'hack bikin telur dadar fluffy' },
  { slug: 'guess-the-price', db: false, best: 'interaktif, tebak harga', face: '✅ faceless', struct: 'tampilkan makanan → "tebak harga" (jeda) → reveal → reaksi murah/mahal → CTA komen', hook: '"tebak berapa harganya?"', ret: 'partisipasi + curiosity gap', ex: 'tebak harga seblak mewah' },
  { slug: 'seasonal-tie-in', db: false, best: 'momen (ramadan, lebaran, musim)', face: '✅ faceless', struct: 'kaitkan momen (hook) → konten relevan momen → ajakan momen → CTA', hook: '"menu takjil paling laku"', ret: 'relevansi waktu → boost + share', ex: 'jajanan buka puasa' },
  { slug: 'origin-story', db: false, best: '"asal usul X", cerita makanan', face: '✅ faceless', struct: 'fakta pembuka misterius → ceritakan asal-usul beat-by-beat → twist sejarah → CTA', hook: '"kenapa seblak namanya seblak?"', ret: 'naratif + edukasi ringan', ex: 'sejarah mie ayam' },
  { slug: 'narrated-compilation', db: false, best: 'FORMAT RAKIT — bungkus formula naratif lain (listicle/fakta/story)', face: '✅ faceless', struct: 'VO arc (tulang cerita) → tiap beat dijodohkan b-roll klip 2-3s (match per-frame/tag) → layer: VO + music −18dB + SFX reaction tiap cut + hard-sub → loop', hook: 'montage cepat 3 cut + janji di VO detik 0', ret: 'pacing kilat (cut 2-3s, no dead air) + narasi nahan sampai habis', ex: '3 jajanan paling satisfying (VO + b-roll campur)' }
]
